### ISSUE TITLE
Missing gnureadline: AttributeError: 'NoneType' object has no attribute 'add_cmd'

### ISSUE THREAD

**Issue by ritiek** [mps-youtube/yewtube#886]
It seems that mps-youtube on develop branch is broken for Python 3.7:
```bash
$ git clone https://github.com/mps-youtube/mps-youtube
$ cd mps-youtube/

$ python3.6 ./mpsyt
# works ok

$ python3.7 ./mpsyt
Traceback (most recent call last):
  File "./mpsyt", line 2, in <module>
    import mps_youtube.main
  File "/home/ritiek/mps-youtube/mps_youtube/__init__.py", line 8, in <module>
    init.init()
  File "/home/ritiek/mps-youtube/mps_youtube/init.py", line 56, in init
    assign_player(config.PLAYER.get)  # Player is not assigned when config is loaded
  File "/home/ritiek/mps-youtube/mps_youtube/util.py", line 546, in assign_player
    module = import_module('mps_youtube.players.{0}'.format(module_name))
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/ritiek/mps-youtube/mps_youtube/players/mpv.py", line 12, in <module>
    from ..player import CmdPlayer
  File "/home/ritiek/mps-youtube/mps_youtube/player.py", line 15, in <module>
    from .commands import lastfm
  File "/home/ritiek/mps-youtube/mps_youtube/commands/__init__.py", line 27, in <module>
    from . import download, search, album_search, spotify_playlist, misc, config, local_playlist
  File "/home/ritiek/mps-youtube/mps_youtube/commands/download.py", line 13, in <module>
    from .search import yt_url, user_pls
  File "/home/ritiek/mps-youtube/mps_youtube/commands/search.py", line 22, in <module>
    from .songlist import plist, paginatesongs
  File "/home/ritiek/mps-youtube/mps_youtube/commands/songlist.py", line 79, in <module>
    @command(r'pl\s+%s' % PL, 'pl')
  File "/home/ritiek/mps-youtube/mps_youtube/commands/__init__.py", line 18, in command
    completer.add_cmd(command)
AttributeError: 'NoneType' object has no attribute 'add_cmd'

```

I traced back and the regression first seems to have been caused by #859.

**Comment by hrnr** [comment]
We really need some CI to catch things like this.

**Comment by tommysolsen** [comment]
Works for me on os x at least.

```

mpsyt version      : 0.2.8
   notes           : released 17 February 2018
pafy version       : 0.5.4 (youtube-dl backend)
youtube-dl version : 2018.09.10
Python version     : 3.7.0 (default, Jul 23 2018, 20:22:55)
[Clang 9.1.0 (clang-902.0.39.2)]
Processor          : i386
Machine type       : x86_64
Architecture       : 64bit,
Platform           : Darwin-17.7.0-x86_64-i386-64bit
sys.stdout.enc     : UTF-8
default enc        : utf-8
Config dir         : /Users/tommy/.config/mps-youtube
env:TERM           : xterm-256color
env:SHELL          : /bin/bash
```

**Comment by ids1024** [comment]
> pip install gnureadline

What? It should be part of the standard library.

https://docs.python.org/3.7/library/readline.html

**Comment by ikuraj** [comment]
mpsyt suddenly started having issues playing (certain) items. No errors were given, sporadically _"MPRIS exited or crashed"_. 

Anyway, I can confirm that installing gnureadline (on my Arch machine, `sudo pip install gnureadline`) fixed the problem. Not sure what's the deal with python and its standard library, as gnureadline is not a separate package (which would make sense if it's in the standard library).

**Comment by ritiek** [comment]
From experience and as mentioned in this [stackoverflow answer](https://stackoverflow.com/a/50454610/6554943), it seems the `gnureadline` does not come with the standard library if python is compiled from source.

**Comment by GokulNC** [comment]
This issue can be solved by adding the dependency `gnureadline` to the `setup.py`'s requirements.
For Windows, it has to be `pyreadline` instead.

@tommysolsen Please fix this.

**Comment by tommysolsen** [comment]
@GokulNC I don't have a Windows machine and therefore can't really ensure that it works, nor do I actually have/develop for python much anymore.

You seem to have some interest in the Windows issues so I assume you do. Would you mind submitting a pull-request for this issue then I'll merge it.

**Comment by airstrike** [comment]
Confirming `pip install pyreadline` works on Windows

**Comment by YugalSharma1** [comment]
> It seems that mps-youtube on develop branch is broken for Python 3.7:
> 
> ```shell
> $ git clone https://github.com/mps-youtube/mps-youtube
> $ cd mps-youtube/
> 
> $ python3.6 ./mpsyt
> # works ok
> 
> $ python3.7 ./mpsyt
> Traceback (most recent call last):
>   File "./mpsyt", line 2, in <module>
>     import mps_youtube.main
>   File "/home/ritiek/mps-youtube/mps_youtube/__init__.py", line 8, in <module>
>     init.init()
>   File "/home/ritiek/mps-youtube/mps_youtube/init.py", line 56, in init
>     assign_player(config.PLAYER.get)  # Player is not assigned when config is loaded
>   File "/home/ritiek/mps-youtube/mps_youtube/util.py", line 546, in assign_player
>     module = import_module('mps_youtube.players.{0}'.format(module_name))
>   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/home/ritiek/mps-youtube/mps_youtube/players/mpv.py", line 12, in <module>
>     from ..player import CmdPlayer
>   File "/home/ritiek/mps-youtube/mps_youtube/player.py", line 15, in <module>
>     from .commands import lastfm
>   File "/home/ritiek/mps-youtube/mps_youtube/commands/__init__.py", line 27, in <module>
>     from . import download, search, album_search, spotify_playlist, misc, config, local_playlist
>   File "/home/ritiek/mps-youtube/mps_youtube/commands/download.py", line 13, in <module>
>     from .search import yt_url, user_pls
>   File "/home/ritiek/mps-youtube/mps_youtube/commands/search.py", line 22, in <module>
>     from .songlist import plist, paginatesongs
>   File "/home/ritiek/mps-youtube/mps_youtube/commands/songlist.py", line 79, in <module>
>     @command(r'pl\s+%s' % PL, 'pl')
>   File "/home/ritiek/mps-youtube/mps_youtube/commands/__init__.py", line 18, in command
>     completer.add_cmd(command)
> AttributeError: 'NoneType' object has no attribute 'add_cmd'
> ```
> 
> I traced back and the regression first seems to have been caused by #859.

I am getting the same error but just the last line is different
>AttributeError: 'NoneType' object has no attribute 'get'

please help me, your method isn't working for me,
I am trying to play youtube songs  through terminal on my old pc, or tell me some other terminal software to do so.
